
name: Terraform Infra (VPC + SG)

on:
  push:
    branches: ["main"]
    paths:
      - "terraform/network/**"
      - "terraform/security/**"
  pull_request:
    paths:
      - "terraform/network/**"
      - "terraform/security/**"

env:
  AWS_REGION: eu-west-1

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform/envs/dev
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: terraform/envs/dev
        run: terraform plan -input=false -no-color

      - name: Terraform Apply
        if: github.event_name == 'push'
        working-directory: terraform/envs/dev
        run: terraform apply -input=false -auto-approve
